name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@43fd7e11ee532218966343a262f10771b5eff978"
        env:
          GITHUB_TOKEN: "f122e7bb3540dfece7fb6024d4924f55c4dd7d15"
env:
    GITHUB_TOKEN: "f122e7bb3540dfece7fb6024d4924f55c4dd7d15"
    LABELS: "!wip,!work in progress,documentation-updated"
    AUTOMERGE: "ready-to-merge"
    AUTOREBASE: "ready-to-rebase-and-merge"
    MERGE_METHOD: "squash"
    MERGE_FORKS: "false"          